// Generated by uniffi-bindgen-react-native
#include "gtfs-importer.h"
#include "generated/gtfs_importer.hpp"

namespace gtfsimporter {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeGtfsImporter::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}