// Generated by uniffi-bindgen-react-native
#include "gtfs-router-rust.h"
#include "generated/gtfs_router.hpp"

namespace gtfsrouterrust {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeGtfsRouter::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}